# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9fdb3f364cb555d88db535f0f10111575bc5e0616fd2a39fa1f0edc19a575a6f45c37f02702d3b9f6abaa58c8630a9a9935b9c8a39fbc3323315b5cb8b1c5f0

test:
  secret_key_base: 9fc2fb13891b7193fcf00c48d401d0f32d99bf44ece2378d899cc37dc5857cd19b541c6e6feba81be9a07494158d5821b551901a0336160bf10b1ba77245cf47

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
